In [2]:
import numpy as np

In [ ]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [50]:
def column_swap(input:np.array)->np.array:    
    return np.fliplr(input)


In [ ]:
#Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [25]:
def compare_two_array(input1:np.array,input2:np.array) ->np.array:
    return (np.where(np.equal(input1,input2)))[0]




[1 2]


In [ ]:
#Készíts egy olyan függvényt, ami vissza adja a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!

In [31]:


def get_array_shape(input_array:np.array):

    if input_array.ndim==2:
        return f"sor: {input_array.shape[0]}, oszlop: {input_array.shape[1]}, melyseg: 1"
    elif input_array.ndim==3:
        return  f"sor: {input_array.shape[1]}, oszlop: {input_array.shape[2]}, melyseg: {input_array.shape[0]}"
    elif input_array.ndim==1:
        return f"sor: 1 , oszlop: {input_array.shape[0]}, melyseg: 1"
    else:
        return "incorrect input"



sor: 2, oszlop: 3, melyseg: 2


In [ ]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges Y-okat egy numpy array-ből. 
#Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [33]:

def encode_Y(input_array:np.array, num:int)->np.array:
    encoded=np.zeros((len(input_array),num))
    encoded[np.arange(len(input_array)),input_array]=1
    return encoded


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [34]:
def decode_Y(input_array:np.array)->np.array:
    return np.argmax(input_array,axis=1)


[1 2 0 3]


In [ ]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza a legvalószínübb element a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. 
# Ki: 'szilva'
# eval_classification()

In [28]:

def eval_classification(classes, prob):
    return classes[np.argmax(prob)]


szilva


In [ ]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# repalce_odd_numbers()

In [ ]:
def replace_odd_numbers(input_array)->np.array:
    return np.where(input_array % 2 == 1, -1, input_array)

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [39]:

def replace_by_value(input_array:np.array,num:int)->np.array:
    return np.where(input_array >= num,1,-1 ) 


[[-1 -1 -1 -1]
 [-1 -1 -1  1]]


In [ ]:
# Készítsd egy olyan függvényt, ami az array értékeit összeszorozza és az eredmény visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [23]:
def array_multi(input_array:np.array)->int:
    return np.prod(input_array) 

24


In [ ]:
# Készítsd egy olyan függvényt, ami a 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [16]:

def array_multi_2d(input_array:np.array)->np.array:
    return np.prod(input_array,axis=1)



[ 2 12]


In [ ]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()


In [22]:
def add_border(input_array:np.array)->np.array:
    return np.pad(input_array, pad_width=1)


[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [ ]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot.
# Be: '2023-03', '2023-04'
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [13]:
def list_days(date1:np.datetime64,date2:np.datetime64)->np.array:
    return np.arange(date1,date2,dtype='datetime64[D]')


['1999-12-29' '1999-12-30' '1999-12-31' '2000-01-01']


In [ ]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD
# Be:
# Ki: 2017-03-24 

In [52]:
def current_date():
    return np.datetime64('now','D')



2023-03-11


In [ ]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:00:00 óta.
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()


In [68]:
def sec_from_1970()->int:
    
    date=(np.datetime64('now')-np.datetime64('1970-01-01T00:00:00'))
    return int(date.item().total_seconds())
print(sec_from_1970())

1678526026
